language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -qy python-software-properties
  - sudo add-apt-repository -y ppa:radio-astro/main
  - sudo apt-get update -q

install:
  - sudo apt-get install -qy cmake flex bison libblas-dev liblapack-dev
      libcfitsio3-dev wcslib-dev libfftw3-dev gfortran libncurses5-dev
      libreadline6-dev libhdf5-serial-dev python-all-dev libboost-dev
      libboost-python-dev python-numpy


before_script:
  - mkdir build
  - cd build
  - wget ftp://ftp.astron.nl/outgoing/Measures/WSRT_Measures.ztar
  - tar zxvf WSRT_Measures.ztar
  - cmake ..
      -DUSE_FFTW3=ON
      -DBUILD_TESTING=ON
      -DUSE_OPENMP=OFF
      -DUSE_HDF5=ON
      -DBUILD_PYTHON=ON
      -DDATA_DIR=$PWD
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - make -j4
  - if [ $BUILD_TYPE == "Debug" ]; then export CASACORE_CHECK=yes; fi
  - make test
  - sudo make install
